# Generated by Django 6.1 on 2026-09-03 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0004_remove_listing_currency_remove_listing_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('created', 'Created'), ('verifying', 'Verifying'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('sold', 'Sold')], default='created', max_length=10)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
            ],
        ),
    ]
