# Generated by Django 6.1 on 2026-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='currency',
            field=models.CharField(choices=[('PLN', 'Polish Złoty'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='PLN', max_length=3),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('sold', 'Sold')], default='draft', max_length=10),
        ),
    ]
