# Generated by Django 6.1 on 2026-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_auction_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
