# Generated by Django 6.1 on 2026-09-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auction_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
