# Generated by Django 6.1.1 on 2026-09-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_auction_options_auction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bids_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
