# Generated by Django 6.1 on 2026-09-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_bid_amount_alter_listing_final_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-created_at', 'listing', 'bid_price']},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='amount',
            new_name='bid_price',
        ),
    ]
