# Generated by Django 6.1 on 2026-09-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_bid_options_rename_amount_bid_bid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sold_date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='starting_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
