# Generated by Django 6.1 on 2026-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_remove_listing_currency_remove_listing_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
