# Generated by Django 6.1 on 2026-09-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_listing_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-creation_date']},
        ),
    ]
