# Generated by Django 6.1 on 2026-09-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_auction_current_price'),
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auction'),
        ),
    ]
