# Generated by Django 6.1 on 2026-09-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='items_amount',
            field=models.IntegerField(default=0),
        ),
    ]
