# Generated by Django 6.1 on 2026-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('mod', 'Moderator'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
