# Generated by Django 6.1.1 on 2026-09-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',)},
        ),
    ]
