# Generated by Django 6.1.1 on 2026-09-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sum_user_rating',
            field=models.BooleanField(default=False),
        ),
    ]
