# Generated by Django 6.1.1 on 2026-09-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auction_processing'),
        ('rating', '0002_rating_created_at_rating_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auction.auction'),
        ),
    ]
