# Generated by Django 6.1.1 on 2026-09-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_auction_options_auction_created_at_and_more'),
        ('rating', '0003_rating_auction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='rating',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auction.auction'),
        ),
    ]
