# Generated by Django 6.1 on 2026-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
