# Generated by Django 6.1.1 on 2026-09-19 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_alter_listing_options'),
        ('watchlist', '0002_watchlist_notifications_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['listing', 'user'], name='watchlist_w_listing_ff97c1_idx'),
        ),
    ]
