# Generated by Django 6.1.1 on 2026-09-19 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_alter_listing_options'),
        ('watchlist', '0004_alter_watchlist_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('listing', 'user', 'notifications_enabled')},
        ),
    ]
