# Generated by Django 6.1.1 on 2026-09-25 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_auction_options_auction_created_at_and_more'),
        ('watchlist', '0006_alter_watchlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.auction'),
        ),
    ]
